import { Octokit } from '@octokit/rest';
import { logger } from '../utils/logger.js';

export interface PRCreationOptions {
  owner: string;
  repo: string;
  title: string;
  body: string;
  head: string;
  base: string;
}

export class PRCreator {
  private octokit: Octokit;

  constructor(token: string) {
    if (!token) {
      throw new Error('GitHub token is required');
    }
    this.octokit = new Octokit({ auth: token });
  }

  /**
   * Create a pull request
   */
  async createPR(options: PRCreationOptions): Promise<number> {
    try {
      logger.startSpinner('pr', 'Creating pull request...');

      const response = await this.octokit.pulls.create({
        owner: options.owner,
        repo: options.repo,
        title: options.title,
        head: options.head,
        base: options.base,
        body: options.body,
      });

      const prNumber = response.data.number;
      const prUrl = response.data.html_url;

      logger.succeedSpinner('pr', `PR #${prNumber} created`);
      logger.info(`PR URL: ${prUrl}`);

      return prNumber;
    } catch (error) {
      logger.failSpinner('pr', 'Failed to create PR');
      throw new Error(`Failed to create PR: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Format PR body from implementation details
   */
  formatPRBody(featureTitle: string, plan: string, filesWritten: string[]): string {
    return `## 🤖 AI-Generated Feature Implementation

**Feature:** ${featureTitle}

### Implementation Plan
${plan.substring(0, 1000)}${plan.length > 1000 ? '...' : ''}

### Files Changed
${filesWritten.map(f => `- \`${f}\``).join('\n')}

### Notes
- This PR was automatically generated by AI Feature Builder
- Please review all changes carefully
- Tests have been generated using AI-Test-Generator
- Manual review and adjustments may be needed

---
*Generated by AI Feature Builder*`;
  }
}

